project/users/urls.py
from django.urls import include, path

from users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"

urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

project/core/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %}CBV3 Django Prototype{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet" />

    {% endblock %}
  </head>

  <body>
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}"
          >Codebuddies</a
        >

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}"
                >Home <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a
                class="nav-link"
                href="{% url 'users:detail' request.user.username  %}"
                >{% trans "My Profile" %}</a
              >
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'account_logout' %}"
                >{% trans "Sign Out" %}</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a
                id="sign-up-link"
                class="nav-link"
                href="{% url 'account_signup' %}"
                >{% trans "Sign Up" %}</a
              >
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a
                id="log-in-link"
                class="nav-link"
                href="{% url 'account_login' %}"
                >{% trans "Sign In" %}</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>

    <div class="container">
      {% if messages %} {% for message in messages %}
      <div
        class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}"
      >
        {{ message }}<button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %} {% block content %}
      <h1>Welcome to Codebuddies!</h1>
      <p>
        Please find some useful commands below to help you get started on Django
        development
      </p>
      <h2>Application urls</h2>
      <ul>
        <li>
          <a href="/api/v1/resources/">/api/v1/resources/ </a> - browse the API
          for resources
        </li>
        <li>
          <a href="/admin/">/admin/ </a> - login using superuser credentials
        </li>
        <li>
          <a href="/auth/obtain_token/">/auth/obtain_token/admin/</a> - get a
          token
        </li>
        <li><a href="/auth/users/">/auth/users/</a> - create a user</li>
      </ul>
      <h2>docker-compose commands</h2>
      <ul>
        <li>
          <code>docker-compose run --rm app ./manage.py createsuperuser</code> - Command
          to create a superuser
        </li>
        <li>
          <code>docker-compose run --rm app pytest</code> - Command to run
          tests
        </li>
        <li>
          <code>docker-compose run --rm app ./manage.py makemigrations</code> - Command to make
          migrations (necessary if you change the models)
        </li>
        <li>
          <code>docker-compose run --rm app ./manage.py migrate</code> - Command to migrate the
          migrations (necessary if you ran the previous makemigrations step)
        </li>
      </ul>
      {% endblock content %}
    </div>
    <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

    <!-- Bootstrap JS and its dependencies-->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}
  </body>
</html>